### ISSUE TITLE
main broken by cross-PR semantic conflict: emit_budget.rs constructs Inst::Load { align } after #900 stage 3 removed the field

### ISSUE THREAD

**Issue by theSherwood** [theSherwood/vm#1047]
`cargo build --workspace --tests` (and therefore every PR's `build · test · fmt · clippy` job, plus the macOS/Windows matrix jobs) fails on main:

```
error[E0559]: variant `svm_ir::Inst::Load` has no field named `align`
  --> crates/svm-wasm-jit/tests/emit_budget.rs:42:17
```

Two independently-green PRs merged into a broken combination:

- `7c5c55bb` "wire rev: cut the align byte + fence-only atomic ordering (#900 stage 3)" removed `align` from `svm_ir::Inst::Load`.
- `12b1c370` / `8b5c1047` (#1038, module-total emit budget, merged via the #1040 branch) added `crates/svm-wasm-jit/tests/emit_budget.rs`, which constructs `Inst::Load { …, align: 3 }`.

Each PR's CI ran against its own pre-merge base, so neither saw the other — the classic merge-skew gap (branch-protection CI without a merge queue / requiring up-to-date branches would have caught it).

**Fix** (one line, delete the stale `align: 3,` field): riding on PR #1045, which inherited the breakage on its first CI run. This issue documents the breakage window on main for anyone bisecting, and flags the merge-skew exposure.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01JVgv3eQTbcVaqJePPZ8jWu
